// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhct1donTe1a073dyxfcbCWX5SaJIYQpI',
    appId: '1:688879812841:android:a82fdb092c06b83100b078',
    messagingSenderId: '688879812841',
    projectId: 'velox-app-1fe81',
    storageBucket: 'velox-app-1fe81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_G2eL1EcFpnIqCls--FVmk1f8onV1n8g',
    appId: '1:688879812841:ios:f45f3c3ca57bcf8d00b078',
    messagingSenderId: '688879812841',
    projectId: 'velox-app-1fe81',
    storageBucket: 'velox-app-1fe81.appspot.com',
    androidClientId: '688879812841-vgs7ud3nc11j5o3nfd25o8pqaopkd0dv.apps.googleusercontent.com',
    iosClientId: '688879812841-bq92gtc5306891pvthvi6aqvilmjcnpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.velox',
  );
}
